[Feat] 홈화면 하이파이로 디자인 수정 및 숫자테이블과 최근소식 통신 코드 추가
HICC-REBOOT/HICC-REBOOT-Frontend pull request #30
Opened 2024-01-25 06:56 UTC by darkenergy814

# 작업 이름 홈화면 디자인 수정

## 주요 변경 내용
- 변경된 디자인으로 홈화면 디자인 수정(투명도 적용 포함)
- 활동에 마우스 호버시 background 사진 size 확대
- 숫자테이블 query 코드 추가
- 최근 소식 query 코드 추가

## 참고 사항
- 버튼에 2중 그라데이션 적용에 문제가 있음

## 남은 작업 내용
- 버튼 호버 시 그라데이션 변경
- 버튼 최종 디자인으로 수정
- 버튼 각종 링크 연결
- 최종 통신 연결 코드 작성

## 참고용 시연 사진
<img width="278" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/c44781f3-69c0-494b-80f6-10ec6f96de85">
<img width="276" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/458668db-6fdb-4df3-ad40-9df9c2727f8f">
<img width="671" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/cbfd241b-a4b7-4828-81ce-5fc307867fc2">
<img width="677" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/43c5864f-0b0a-48ee-b127-300de9788bf7">
<img width="679" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/b2bbe94e-bfd1-40ca-9324-94d6dc1fd933">
<img width="676" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/2f1630eb-f9f2-4c14-a9ea-a3ef966abf94">
<img width="673" alt="image" src="https://github.com/HICC-REBOOT/HICC-REBOOT-Frontend/assets/79552567/9ffc796e-0e38-40d1-a843-40a64c2fcab3">

2024-01-25 15:49 UTC, jinhokim98 requested changes
css prefix 붙여주시는 것 해결해주세요. 안 붙이면 충돌나요,..

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/components/common/popup/withdrawal/withdrawal.style.css
> +.ant-modal-wrap {
전 pr comment와 동일합니다. 앞에 prefix 붙여주세요

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/components/home/HongMap.tsx
> +                <Check fill="#5B4EF5" />
정의되어있지 않은 색인가요?

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/components/home/JoinUs.tsx
> +            <StarL width={'2.2rem'} height={'2.2rem'} />
svg 파일을 ReactComponent형태로 불러올 경우 width와 height를 따로 정의해서 쓸 필요가 없습니다.

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/components/home/style/Activity.style.tsx
> +    background-size: 200%;
figma comment를 보면 민님은 scale: 1.2로 작업하셨다고 했는데 이렇게 적용하는 것과 큰 차이가 없을까요?

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/query/get/useGetLatestNews.tsx
> +  content: [
content안의 내용이 전부 동일한데 3개로 작성하신 이유가 있을까요?

2024-01-25 15:49 UTC, jinhokim98 commented on frontend/src/query/get/useGetLatestNews.tsx
> +      uri: '/api/main/latest-news?page=0&size=3',
?뒤에 있는 것은 파라미터로 보입니다.
3번째 제네릭 타입을 이용하면 파라미터를 더 간단하게 쓸 수 있습니다.

```ts
interface Parameter {
  page:  number;
  size: number;
}

const response = await request<null, News, Parameter>({
  uri: '/api/main/latest-news',
  method: 'get',
  params: {
    page: 0,
    size: 3,
  }
});
```

2024-01-26 10:45 UTC, darkenergy814 commented on frontend/src/components/common/popup/withdrawal/withdrawal.style.css
> +.ant-modal-wrap {
네, 수정 했습니다.

2024-01-26 10:53 UTC, darkenergy814 commented on frontend/src/components/home/HongMap.tsx
> +                <Check fill="#5B4EF5" />
아니요 point1 색 입니다. 수정했습니다.

2024-01-26 10:54 UTC, darkenergy814 commented on frontend/src/components/home/JoinUs.tsx
> +            <StarL width={'2.2rem'} height={'2.2rem'} />
screen 종류에 따라  달라지는 component라 width, height를 따로 지정해줬습니다.

2024-01-26 10:57 UTC, darkenergy814 commented on frontend/src/components/home/style/Activity.style.tsx
> +    background-size: 200%;
아 깜빡하고 임의로 지정했네요. 수정 했습니다!

2024-01-26 10:58 UTC, darkenergy814 commented on frontend/src/query/get/useGetLatestNews.tsx
> +  content: [
article 총 3개를 불러와서 3개로 해놨는데 수정해야될까요?

2024-01-26 10:59 UTC, darkenergy814 commented on frontend/src/query/get/useGetLatestNews.tsx
> +      uri: '/api/main/latest-news?page=0&size=3',
최근 소식 3개를 불러오는 것으로 고정된 상항이라 상관 없지 않나요?

2024-01-26 14:45 UTC, jinhokim98 commented on frontend/src/query/get/useGetLatestNews.tsx
> +  content: [
이거는 수정해야합니다.!

2024-01-26 14:47 UTC, jinhokim98 commented on frontend/src/query/get/useGetLatestNews.tsx
> +      uri: '/api/main/latest-news?page=0&size=3',
상관없긴한데ㅋㅋㅋ 미관상...ㅋㅋㅋ 뭐 큰 상관은 없어요

2024-01-26 14:49 UTC, jinhokim98 approved these changes

2024-01-26 14:49 UTC, merged